version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /Users/duytc/Documents/Docker/Docker-data/Mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: duytc
    ports:
      - '3306:3306'
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - /Users/duytc/Documents/Docker/Docker-data/cassandra:/var/lib/cassandra

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
