server:
  port: 9000
spring:
  application:
    name: login-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false
    username: root
    password: duytc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        momentsUserChanged:
          destination: moments.user.changed
          contentType: application/json
  security:
    user:
      name: duytc
      password: duytc

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

configJwt:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

#  jwt:
#    uri: /auth/**
#    header: Authorization
#    prefix: Bearer
#    expiration: 86400
#    secret: JwtSecretKey
#
#  service:
#    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
#    password: ef919ae4-b893-4969-b782-57978180ad33